### ISSUE TITLE
versionist version tag starting again

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-nodered#15]
versionist started versioning from v0.0.2, even if there was already a v0.1.0 tag.

@craig-mulligan, how are we supposed to bootstrap versionist? Where does it look for previous tags?

**Comment by craigmulligan** [comment]
It gets it from `getChangelogDocumentedVersions`.  So you can add an initial entry to CHANGELOG.md or pass the the current version to the `--current` flag. https://github.com/resin-io/versionist#--current.

**Comment by cskiraly** [comment]
It seems it needs both the entry in the CHANGELOG and the version tag in git.
Works now
