### ISSUE TITLE
Dynamic addition of custom node

### ISSUE THREAD

**Issue by dpap** [Agile-IoT/agile-nodered#8]
following the steps shown in https://nodered.org/docs/creating-nodes/first-node to add a custom node I have added the required .html and .js file to the shared folder of the agile-nodered container

I am getting the following message when agile-nodered starts up even though the files are visible inside the container 

root@agile-nodered:/opt/secure-nodered/.nodered/nodes# ls
lower-case.html  lower-case.js

1 Jun 13:16:19 - [info] Dashboard up and running
1 Jun 13:16:20 - [info] Dashboard version 2.3.10 started at /api/ui
1 Jun 13:16:20 - [warn] ------------------------------------------------------
1 Jun 13:16:20 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
1 Jun 13:16:20 - [warn] [lower-case] Error: Cannot find module '.nodered/nodes/lower-case.js'
1 Jun 13:16:20 - [warn] ------------------------------------------------------
1 Jun 13:16:20 - [info] User directory : ./.nodered/
1 Jun 13:16:20 - [info] Flows file     : .nodered/flows_agile-nodered.json
1 Jun 13:16:20 - [info] Starting flows

**Comment by cskiraly** [comment]
Seems to be an issue either with the node-red version we use, or with the way we embed it.
It picks up nodes from /opt/secure-nodered/.nodered/nodes (i.e. \<the folder mounted from the host\>/nodes), puts them in .config.json, but then it errs out with "cannot find module", even if the file is there.

The problem might be the relative path it uses, so as a test, I was trying to change the path in the .config.json to an absolute path. However, this is overwritten at start with the relative path, which then provides the same error.

The file handling all this loading logic seems to be in https://github.com/node-red/node-red/blob/0.16.2/red/runtime/storage/localfilesystem.js
@nopbyte, ideas?

**Comment by cskiraly** [comment]
fixed in https://github.com/Agile-IoT/agile-nodered/pull/16
